### ISSUE TITLE
tensorflow-gpu版本

### ISSUE THREAD

**Issue by SSTato** [bubbliiiing/keras-face-recognition#10]
tensorflow-gpu这个版本太低了吧，和我的cuda不匹配，重新安装cuda好麻烦，有没有别的办法啊，或者有没有其他可以实时人脸识别的代码模型了呀，救救孩子吧

**Comment by bubbliiiing** [comment]
这个代码一百年前的了…

**Comment by bubbliiiing** [comment]
用pytorch的吧
